# Generated by Django 2.2.5 on 2021-10-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleinfo',
        ),
    ]
